# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
services:
  keel_tests:
    image: ${IMG_KEEL_TESTS}
    container_name: keel_tests
    build:
      context: .
      dockerfile: Dockerfile.tests