FROM golang:1.26.5
COPY . /go/src/github.com/keel-hq/keel
WORKDIR /go/src/github.com/keel-hq/keel
RUN make install-debug

FROM node:24.11.0-alpine
WORKDIR /app
COPY ui/package.json ui/package-lock.json /app/
RUN npm ci
COPY ui /app
RUN npm run typecheck && npm run lint && npm test && npm run build

FROM golang:1.26.5

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

VOLUME /data
ENV XDG_DATA_HOME /data

COPY --from=0 /go/bin/keel /bin/keel
COPY --from=1 /app/dist /www
COPY --from=0 /go/bin/dlv /
#ENTRYPOINT ["/bin/keel"]
ENTRYPOINT ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/bin/keel"]

EXPOSE 9300
EXPOSE 40000
